### ISSUE TITLE
Expose notification data as one big JSON object

### ISSUE THREAD

**Issue by lucalabs-de** [lucalabs-de/end#12]
Since JSON is nice to work with in eww's expressions, it would be cleaner to expose all notification data as a single JSON object instead of 7 different parameters.

**Comment by VixieTSQ** [comment]
I think if we do this, we will be outgrowing serializing JSON on our own. Worth bringing in a library but I don't know what the serialization ecosystem looks like in haskell.

**Comment by VixieTSQ** [comment]
> I think if we do this, we will be outgrowing serializing JSON on our own. Worth bringing in a library but I don't know what the serialization ecosystem looks like in haskell.

In addition to this, I realized I screwed up my serialization and didn't put quotes around the object keys. So even more reason to do this.

**Comment by lucalabs-de** [comment]
> I think if we do this, we will be outgrowing serializing JSON on our own. Worth bringing in a library but I don't know what the serialization ecosystem looks like in haskell.

The standard is [aeson](https://hackage.haskell.org/package/aeson), but I'm not so sure about using a library. We have to encode a map of Variant types, and forcing this into aeson's types might be more effort than writing the serialization logic ourselves. I'm thinking a function that pattern-matches the different Variant types and recursively encodes maps. It might be annoying though to encode the hints map differently than the actions map, so aeson might be the nicest solution after all.

**Comment by lucalabs-de** [comment]
Done.
