### ISSUE TITLE
Update & improve example config

### ISSUE THREAD

**Issue by lucalabs-de** [lucalabs-de/end#15]
The example config in EXAMPLE.md still uses the old notification syntax and doesn't show how to work with notification images. Also, it might be useful to include the config as actual files instead of Markdown.

**Comment by lucalabs-de** [comment]
The screenshot in the README should probably also be updated.

**Comment by pink10000** [comment]
any progress on this?

**Comment by lucalabs-de** [comment]
Done @pink10000
